#!/bin/bash

#run clean to delete all files created by any scripts, to prevent any duplication/errors
rm filtered_crawling.txt
rm -r getbootstrap.com
rm -r www.taco.com
rm -r www.uvic.ca

#./script1
#./script2
echo 'good to go!'
